import '@/styles/globals.css';

import { Inter } from 'next/font/google';
import { cookies } from 'next/headers';

import { TRPCReactProvider } from '@/trpc/react';
import { getServerAuthSession } from '@/server/auth';
import { getSession } from 'next-auth/react';

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-sans',
});

export const metadata = {
  title: 'Create T3 App',
  description: 'Generated by create-t3-app',
  icons: [{ rel: 'icon', url: '/favicon.ico' }],
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className="h-full w-full">
      <body className={`font-sans ${inter.variable} h-full w-full`} suppressHydrationWarning>
        <TRPCReactProvider cookies={cookies().toString()}>{children}</TRPCReactProvider>
      </body>
    </html>
  );
}
